version:     "0007--06-Nov-2022"
copyright:   "2022"
author:      "Joselin Permata Aprillia"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/joselinprmt/os222/"
myloglink:   "/TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
